# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: 'docs/models.txt'
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
    - id: python-no-eval
    - id: python-no-log-warn
    - id: python-use-type-annotations
    - id: rst-backticks
